### ISSUE TITLE
BlizzardAppInfos class protection level

### ISSUE THREAD

**Issue by EricBatlle** [ZeShmoutt/Blizzard-API-For-Unity#3] opened 2020-09-29 15:12 UTC
Hi ZeShmoutt, it's me again ^^' 
This time I hope to help instead of making you dizzy with my doubts :D

When importing your API to Unity, it shows a repeated error message:

`Assets\Scripts\_Core\Editor\BlizzardAppInfos_Editor.cs(8,23): error CS0122: 'BlizzardAppInfos' is inaccessible due to its protection level`

Those are related with BlizzardAppInfos, it's easy to solve but maybe some beginer can panic, just add "public" to `BlizzardAppInfos `class and done ^^!

**Comment by ZeShmoutt** [comment] 2020-09-29 17:11
What version of Unity and package do you use ? I can't reproduce it.

**Comment by EricBatlle** [comment] 2020-09-29 17:26
I'm not using Package Manager, I'm simply copy-pasting scripts folder

**Comment by ZeShmoutt** [comment] 2020-09-29 17:36
That doesn't answer the question, though. Also, if you only copy the scripts folder, you'll be missing the assembly definition file which is pretty important.

**Comment by EricBatlle** [comment] 2020-09-29 17:43
I'm using Unity 2019.3.1f1. (I just read that readme says that only for 2018 and older is recommended to make a copy-paste, but will do the same problem I think)

Hmmm I see, but appart from auto-importing EditorCoroutines, what else do the assembly definition file?

**Comment by EricBatlle** [comment] 2020-09-29 18:01
But yes, it doesn't show the error if imported via Package Manager, I've tested right now, but I don't really know why, class protection is the same :/

**Comment by ZeShmoutt** [comment] 2020-09-29 18:06
The short version is that it separates the entire plugin into its own assembly, so you can only access what is explicitely marked as `public`. It also allows custom version defines based on dependancies, that I use to cut code if you don't have the editor coroutines package installed. It doesn't install dependancies by itself, though.

Also why the hell did you install it by copying the Scripts folder while there's an *official* tool for importing custom packages from github ? It makes absolutely no sense to me.

**Comment by EricBatlle** [comment] 2020-09-29 18:11
I understand.

Why? Rear case, I've downloaded couple of days ago the repo (.zip) and when I was trying to add the package I have no internet connection, so instead loading via Git, I grabbed the package from the last day downloads, copy Scripts folder, and voilá.

**Comment by ZeShmoutt** [comment] 2020-09-29 18:36
Well, the simple answer is that you had a bug because you didn't read the manual.

**Closed as completed** 2020-09-29 18:46 UTC
Labels: bug, wontfix
